import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import "remixicon/fonts/remixicon.css";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";

const fontBaru = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata = {
  title: "Portofolio saya",
  description: "Generated by Sendy",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth bg-black text-white ">
      <body className={`${fontBaru.className}antialiased`} id="beranda">
        <ScrollToTop />
        <Navbar />
        <div className="container mx-auto px-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
